---
tasks:
  1:
    class: MyClass1
    sub-tasks:
      a:
        description: Program something cool
          with some amzing tools
        points: 3
        code-snippets:
          -
            type: METHOD
            name: getNumber
          -
            type: CONSTRUCTOR
          -
            type: ATTRIBUTES
          -
            type: CLASS
      b:
        description: Another cool program
        points: 1
        code-snippets:
          -
            type: CLASS
  2:
    class: MyClass2
    sub-tasks:
      a:
        description: Program something cool
          with some amzing tools
        points: 3
        code-snippets:
          - type: METHOD
            name: getNumbers
          - type: ATTRIBUTES
          - type: CLASS
      b:
        description: Another cool program
        points: 1
        code-snippets:
          - type: METHOD
              name: getN